version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=golang

  lines-provider:
    image: antonboom/lines-provider

  sport-line-processor:
    build: ./
    ports:
      - '8090:8090'
      - '8091:8091'
